version: '3'
services:
  client-app:
    depends_on:
      - backend
    build:
      context:
        ./frontend
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - DATABASE_URL=postgresql://testusr:password@postgres:5432/testdb
    networks:
     - web_nw
  backend:
    build:
      context:
        ./backend
    volumes:
      - ./migrations:/var/app/migrations
    depends_on:
      - postgres
    networks:
     - web_nw
     - db_nw
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_nw

networks:
  web_nw:
    driver: bridge
  db_nw:
    driver: bridge
