version: '3'
services:
  reverse-proxy:
    build:
      context:
        ./backend/nginx
    volumes:
      - site-data:/var/www/car_notifier/html
    networks:
      - web_nw
      - db_nw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context:
        ./frontend
    volumes:
      - site-data:/app/site-data
    networks:
     - web_nw

  backend:
    build:
      context:
        ./backend
    volumes:
      - ./migrations:/var/app/migrations
    environment:
      - DATABASE_URL=postgresql://testusr:password@postgres:5432/testdb
    depends_on:
      - postgres
    networks:
     - web_nw
     - db_nw

  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_nw

networks:
  web_nw:
    driver: bridge
  db_nw:
    driver: bridge

volumes:
  site-data:
