version: '3'
services:
  client-app:
    depends_on:
      - backend
    build:
      context:
        ./frontend
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
     - web_nw
  backend:
    build:
      context:
        ./backend
    networks:
     - web_nw

networks:
  web_nw:
    driver: bridge
