version: '3'
services:
  client-app:
    build:
      context:
        ./frontend
    ports:
      - "5000:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
  backend:
    build:
      context:
        ./backend
    ports:
      - "5001:5000"
